version: "3.8"

services:
  traefik:
    image: traefik:v2.8
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.http.address=:80"
    ports:
      - "80:80"
      - "8080:8080" # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  www-maintenance-override:
    image: nginx:stable
    volumes:
      - ./www-maintenance-override/pages:/usr/share/nginx/html
      - ./www-maintenance-override/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: "true"
      traefik.http.services.www-maintenance-override.loadbalancer.server.port: 80
      traefik.http.routers.www-maintenance-override.entrypoints: http
      traefik.http.routers.www-maintenance-override.rule: Host(`192.168.1.6.nip.io`) && PathPrefix(`/maintenance-override/`)
      traefik.http.routers.www-maintenance-override.priority: 110
      traefik.http.services.www-maintenance-override.healthcheck.path: / # Check root path
      traefik.http.services.www-maintenance-override.healthcheck.interval: 30s
      traefik.http.services.www-maintenance-override.healthcheck.timeout: 5s
      traefik.http.services.www-maintenance-override.healthcheck.retries: 3
    ports:
      - "8081:80"  # Map Nginx to port 8081 on the host for direct access
      
  www:
    image: nginx  # Main application image
    volumes:
      - ./path/to/your/app:/usr/share/nginx/html  # Adjust this to your app's path
    labels:
      traefik.enable: "true"
      traefik.http.routers.www.rule: Host(`192.168.1.6.nip.io`) && HeadersRegexp(`Cookie`, `maintenance-override=true`)
      traefik.http.services.www.loadbalancer.server.port: 80  # Ensure this is the port your app listens on
      traefik.http.services.www.healthcheck.path: /health  # Assuming your app exposes a health check endpoint
      traefik.http.services.www.healthcheck.interval: 30s
      traefik.http.services.www.healthcheck.timeout: 5s
      traefik.http.services.www.healthcheck.retries: 3
